### ISSUE TITLE
Plotting data corrupted?

### ISSUE THREAD

**Issue by Holoratte** [FredericG-BE/ardumower#5]
Hi Frederic,

after further more testing, I have seen some corrupt data arrive using ESP8266 while plotting motor control and perimeter at heavy use situations: in this case the sonar was triggered while plotting motor control.  

![double data](https://cloud.githubusercontent.com/assets/12900571/9978272/940b02f6-5f26-11e5-9362-094a27da85af.JPG)

Is there a kind of handshake possible or already implemented in the ESP firmware? 
Checksum would be a nice feature?

Chris

**Comment by Holoratte** [comment]
I just realized that data corruption is happening almost all the time for motor control plotting:

Plot data: 1000.59,24.91,25.85,**2525.47,2524.53**,173.00,166.00,0.57,-1.32
Plot data: 1000.78,25.85,25.28,**2524.72,2525.28**,165.00,169.00,-1.13,0.00
Plot data: 1000.98,23.96,25.47,**2525.75,2524.25**,173.00,164.00,1.79,-1.23
Plot data: 1001.19,23.96,25.47,**2525.75,2524.25**,179.00,160.00,1.79,-1.23
Plot data: 1001.39,25.09,23.77,**2524.34,2525.66**,171.00,174.00,-0.75,1.89

**Comment by FredericG-BE** [comment]
Hi Chis,
Thanks for reporting, I will look into it.
Frederic

**Comment by Holoratte** [comment]
fault in code pfod.cpp...
